site_name: Docs - Litai Tech
site_url: https://docs.litai.tech
theme:
  favicon: assets/favicon.webp
  logo: assets/logo.webp
  name: material
  palette:
    scheme: slate

markdown_extensions:
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences